### ISSUE TITLE
Backup of favourites

### ISSUE THREAD

**Issue by ripern** [johannilsson/sthlmtraveling#63]
Would be nice to be able to switch phones and not lose the favourites.

**Comment by ripern** [comment]
@johannilsson Har något ändrats relaterat till var favoriterna lagras? Vad tror du om att man skriver ned den till shared prefs när de läses ut från dbn, synkar dem, å sen lyssnar på shared pref förändringar å i event handlern skriver dem till dbn?

**Comment by johannilsson** [comment]
@ripern Nej det är samma som tidigare. Jag skulle inte vilja gå över till att enbart använda shared prefs, men att synka skrivningar skulle kunna vara en lösning. Kan vara värt ett test iaf. Borde fungera att serialisera till och från json.
