### ISSUE TITLE
Crowdsource metro exits

### ISSUE THREAD

**Issue by arooooon** [johannilsson/sthlmtraveling#73]
It would be great if the map could show each and every tunnelbaneuppgång for each station exactly where it is and where the back and front of your train is. We could crowdsource this somehow.

One should also be able to switch to satellite view, this helps a lot in recognizing the environment.

**Comment by johannilsson** [comment]
This would be great to get in, I have some parts of this running but I think it would be better to start fresh again.

How about creating a separate app for just mapping the entrances initially. They could be fetched from OSM as well, but there's some value to have it mapped separate as well.

I'll create a separate issue for the satellite request.

**Comment by arooooon** [comment]
Yes a separate app would be great. Or maybe something linked from the settings of the real app..

Vi borde kolla på det grafiska först.  Varje utgång borde vara färgad efter linjerna samt ha stationsnamn kanske.

Typ såhär:
![typ](https://cloud.githubusercontent.com/assets/5459101/12315700/68047b84-ba7e-11e5-8301-bc01d16b1c2e.png)

Nu går ju inte alla tre linjerna vid mariatorget..men

**Comment by johannilsson** [comment]
Finns det exempel där det inte går att ta sig från en ingång till en linje?

Jag tänker att man skulle kunna visa var på tåget man optimalt bör vara separerat från ingångarna?

**Comment by arooooon** [comment]
> Finns det exempel där det inte går att ta sig från en ingång till en linje?

Det tror jag inte, men vid tcentralen och kanske Fridhemsplan får man ju ta en omväg om man går ner i ingången som leder direkt till blåa linjen (Max Vasagatan), men ska till gröna.

> Jag tänker att man skulle kunna visa var på tåget man optimalt bör vara separerat från ingångarna?

Vid adressök då menar du ?

**Comment by johannilsson** [comment]
Var på tåget man bör vara tänker jag att vi skulle kunna visa i samband med den detaljerade informationen för en resa.

Däremot kan det vara en bra idé att även spara ner information om linje och transporttyp till entréer.

Behöver vi något mer för entréer tro?

* Stationsnamn
* Stations id
* Enténamn
* Typ, metro, bus etc...
* Primärt transportslag + linje, en eller flera

**Comment by arooooon** [comment]
Låter bra, men också såklart entrens position.

Vad tror du om att dölja insamlingfunktionen i inställningarna i huvudappen? Jag tror inte det blir något större missbruk där.

**Comment by johannilsson** [comment]
Efter att ha funderat lite mer på det här så tror jag att vi ska köra på OpenStreetMap för entréer. Det finns redan idag en hel del data där men det behöver dock kompletteras.

Om du är sugen på att hjälpa till att mappa entréer där maila mig gärna så kan jag hjälpa till att komma igång med det.

**Comment by johannilsson** [comment]
Stänger denna då vi nu har stöd för entréer.
