### ISSUE TITLE
Duplicates in recents list

### ISSUE THREAD

**Issue by ElectricCookie** [johannilsson/sthlmtraveling#78]
![Screenshot of the issue](http://i.imgur.com/bSSM9Mv.png)

When searching for a route multiple times it gets added to the recents screen multiple times as well, even though the query is exactly the same. This clutters up the list very quickly. I would suggest simply moving up the already existing item.

**Comment by johannilsson** [comment]
Thanks for the report. I've just verified that in some cases it creates entries when it should not.

However for some queries it's expected to create multiple entries e.g, adding/changing a via point, toggling of alternative stops, change of transport modes and or change of origin or destination.

Thanks!

**Comment by ElectricCookie** [comment]
It would be nice if the entered time/date would be saved as well. Maybe also shown in the list so that you can "prepare" a trip.

**Comment by johannilsson** [comment]
@ElectricCookie What you describe might fit with #50?

**Comment by ElectricCookie** [comment]
Yeah I suppose you would need the functionality of #50 to realize this feature

**Comment by ElectricCookie** [comment]
Apparently you can also add duplicate favorites. I suppose it's the same underlying cause.

**Comment by johannilsson** [comment]
Yes, the comparison is the same for both. I suppose that's where the problem for this issue is as well since it's comparing the serialised format and not the actual content.

**Comment by johannilsson** [comment]
We should change the implementation for comparison, it's just a matter of time until this will hit us again.
