### ISSUE TITLE
No loading indicator when pressing "earlier" or "later" connections

### ISSUE THREAD

**Issue by ElectricCookie** [johannilsson/sthlmtraveling#79]
![Screenshot of the issue](http://i.imgur.com/Ewhy33e.png)

Even though it is a very small detail it could drastically improve the experience. Simply replacing the downwards/upwards arrow with a small indeterminate loading indicator to show that something is happening.

**Comment by johannilsson** [comment]
Thanks, that's a great idea to indicate that something is going on as you said.

Cheers!
