### ISSUE TITLE
Errors in time when changing DST 

### ISSUE THREAD

**Issue by loffa** [johannilsson/sthlmtraveling#81]
Planned trip from Häggvik to Högdalen show as an 8 minute trip where I should take the bus for 23h 17m and the commuter train for 28m. This regards trips taken during the time change between 02 and 03 on the DST-change day.

**Comment by johannilsson** [comment]
Thanks for the report.

Looks like the 8 min trip duration can be reproduced. I'll look into the cause of it.

Thanks

**Comment by loffa** [comment]
Got a picture of the error here

![received_10209348584344999](https://cloud.githubusercontent.com/assets/707979/19840524/fbf4efdc-9ef7-11e6-897c-7a52ce477c48.jpeg)
